ToDoListApplication/Models/Pager.cs
namespace ToDoListApplication.Models
{
    public class Pager<T>
    {
        public int CurrentPage { get; set; }

        public int PageCount { get; set; }
        public int TotalCount { get; set; }

        public int PageSize { get; set; }

        public IEnumerable<T> Items { get; set; }
    }
}

ToDoListApplication/Models/Pageres.cs
using Azure;

namespace ToDoListApplication.Models
{
    public class Pageres<T>
    {
        public string SearchDay { get; set; }
        public string SearchMonth { get; set; }
        public string SearchYear { get; set; }
        public Pager<T> Items { get; set; }
    }
}

ToDoListApplication/Models/ToDoListModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoListApplication.Models
{
    public class ToDoListModel
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        public string NameTask { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public DateTime DateOfTask { get; set; }

    }
}

ToDoListApplication/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoListApplication.Data;

namespace ToDoListApplication.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CalendarController : ControllerBase
    {
        private readonly ApplicationDbContext _db;


        public CalendarController(ApplicationDbContext db)
        {
            _db = db;
        }
        [Route("FindAllEvents")]
        public IActionResult OnGetFindAllEvents()
        {
            var events = _db.ToDoLists.Select(e => new
            {
                id = e.Id,
                title = e.NameTask,
                desc = e.Description,
                date = e.DateOfTask
            }).ToList();


            return new JsonResult(events);
        }
    }
}

ToDoListApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoListApplication.Data;
using ToDoListApplication.Interfaces;
using ToDoListApplication.Models;

namespace ToDoListApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHomeControllerService service;


        public HomeController(ApplicationDbContext db, IHomeControllerService service)
        {
            _db = db;
            this.service = service;
        }

        //GET
        public IActionResult Index(string? searchDay, string? searchMonth, string? searchYear, int pg = 1)
        {

            const int pageSize = 10;
            if (pg < 1)
                pg = 1;

            return View(new Pageres<ToDoListModel>
            {
                Items = service.SearchPaged(searchDay, searchMonth, searchYear, pageSize, pg),
                SearchDay = searchDay,
                SearchMonth = searchMonth,
                SearchYear = searchYear

            });

        }

       // public IActionResult Index() => View(service.GetAllTasks());
       
        //GET
        public IActionResult Create()
        {

            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDoListModel task)
        {

            if (ModelState.IsValid)
            {
                service.CreateNewTask(task);
                return RedirectToAction("Index");
            }
            return View(task);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var taskFromDb = _db.ToDoLists.Find(id);
            if (taskFromDb == null)
            {
                return NotFound();
            }
            return View(taskFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ToDoListModel task)
        {

            if (ModelState.IsValid)
            {
                service.UpdateTask(task);
                TempData["success"] = "Task updated successfully";
                return RedirectToAction("Index");
            }
            return View(task);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var taskFromDb = _db.ToDoLists.Find(id);
            if (taskFromDb == null)
            {
                return NotFound();
            }
            return View(taskFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.ToDoLists.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            service.DeleteTask(obj);
            TempData["success"] = "Task deleted successfully";
            return RedirectToAction("Index");

            return View(obj);
        }

    }
}

ToDoListApplication/Views/Calendar/Index.cshtml
@page
@model ToDoListModel

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css"
          rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.1/fullcalendar.min.css" type="text/css"
          rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <br />
                <div id="bootstrapModalFullCalendar"></div>
            </div>
        </div>
    </div>
    <div id="fullCalModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">x</span>
                        <span class="sr-only">close</span>
                    </button>
                    <h4 id="modalTitle" class="modal-title"></h4>
                </div>
                <div id="modalBody" class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <a class="btn btn-primary" id="eventUrl" target="_blank">Event Page</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.2/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.1/fullcalendar.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#bootstrapModalFullCalendar').fullCalendar({
                header: {
                    left: '',
                    center: 'prev title next',
                    right: ''

                },
                eventClick: function (event, jsEvent, view) {
                    $('#modalTitle').html(event.title);
                    $('#modalBody').html(event.desc);
                    $('#eventUrl').attr(event.url);
                    $('#fullCalModal').modal();
                    return false;
                },
                events: 'https://localhost:7014/?handler=FindAllEvents'
            });
        });
    </script>
</body>
</html>

ToDoListApplication/Views/Home/Create.cshtml
@model ToDoListModel

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add task</h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="DateOfTask"></label>
            <input asp-for="DateOfTask" class="form-control" />
            <span asp-validation-for="DateOfTask" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="NameTask"></label>
            <input asp-for="NameTask" class="form-control" />
            <span asp-validation-for="NameTask" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

ToDoListApplication/Views/Home/Delete.cshtml
@model ToDoListModel

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border pt-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete task</h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All">*@

        @*</div>*@
        <div class="mb-3">
            <label asp-for="DateOfTask"></label>
            <input asp-for="DateOfTask" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="NameTask"></label>
            <input asp-for="NameTask" disabled class="form-control"/>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled class="form-control" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

ToDoListApplication/Views/Home/Edit.cshtml
@model ToDoListModel

<form method="post" asp-action="Edit">
    <div class="border pt-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit task</h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All">*@

        @*</div>*@
        <div class="mb-3">
            <label asp-for="DateOfTask"></label>
            <input asp-for="DateOfTask" class="form-control" />
            <span asp-validation-for="DateOfTask" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="NameTask"></label>
            <input asp-for="NameTask" class="form-control" />
            <span asp-validation-for="NameTask" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back To List
        </a>
    </div>
</form>

ToDoListApplication/Views/Home/Index.cshtml
@model Pageres<ToDoListModel>


@{
    ViewData["Title"] = "Index";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">ToDo List</h2>
        </div>
        <div class="col-6 text-end" style="padding: 2pt">
            <a asp-controller="Home" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Add new task
            </a>

            <form asp-controller="Home" asp-action="Index" method="get" style="margin-top:5pt">
                <p>
                    Enter the desired day: <input type="text" name="SearchDay" />
                </p>
                <p>
                    Enter the desired month: <input type="text" name="SearchMonth" />
                </p>
                <p>
                    Enter the desired year: <input type="text" name="SearchYear" />
                </p>
                <p>
                    <input type="submit" value="Filter" />
                </p>
            </form>

        </div>
    </div>
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Date
                </th>
                <th>
                    Title
                </th>
                <th>
                    Description
                </th>
            </tr>
        </thead>
        @foreach (var obj in Model.Items.Items)
        {
            <tr>
                <td width="50%">
                    @obj.DateOfTask.ToString("g")
                </td>
                <td width="30%">
                    @obj.NameTask
                </td>
                <td width="30%">
                    @obj.Description
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Home" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                            <i class="bi bi-pencil-square"></i> &nbsp; Edit
                        </a>
                    </div>
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Home" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            <i class="bi bi-trash3"></i> &nbsp; Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </table>
    @{
        var prevDisabled = Model.Items.CurrentPage == 1 ? "disabled" : "";
        var nextDisabled = Model.Items.PageCount == Model.Items.CurrentPage ? "disabled" : "";
    }
    <a asp-action="Index"
       asp-route-pg="@(Model.Items.CurrentPage-1)"
       asp-route-SearchString="@Model.SearchDay"
       asp-route-SearchString="@Model.SearchMonth"
       asp-route-SearchString="@Model.SearchYear"
       class="btn btn-default @prevDisabled">
        Previous
    </a>

    <a asp-action="Index"
       asp-route-pg="@(Model.Items.CurrentPage+1)"
       asp-route-SearchString="@Model.SearchDay"
       asp-route-SearchString="@Model.SearchMonth"
       asp-route-SearchString="@Model.SearchYear"
       class="btn btn-default @nextDisabled">
        Next
    </a>
</div>

ToDoListApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoListApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoListApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoListApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                     @*   <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index" asp-page-handler="FindAllEvents">Calendar</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoListApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>